
[functions.analyze-trade]
enabled = true
verify_jwt = false
import_map = "./functions/analyze-trade/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/analyze-trade/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/analyze-trade/*.html" ]

[functions.weekly-summary]
enabled = true
verify_jwt = false
import_map = "./functions/weekly-summary/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/weekly-summary/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/weekly-summary/*.html" ]
